Resources:
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.usersTable}
      AttributeDefinitions:
        - AttributeName: email
          AttributeType: S
        # - AttributeName: id
        #   AttributeType: S
      KeySchema:
        - AttributeName: email
          KeyType: HASH
        # - AttributeName: id
        #   KeyType: RANGE
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
