FROM node:12.16
WORKDIR /paralogs

COPY ./package.json .
COPY ./tsconfig.json .
COPY ./yarn.lock .
COPY ./packages/shared/package.json ./packages/shared/
COPY packages/back-logbook ./packages/back/

RUN yarn global add typescript@3.8
RUN yarn install

COPY ./packages/shared ./packages/shared/
COPY packages/back-logbook ./packages/back/

WORKDIR /paralogs/packages/shared
RUN yarn build

WORKDIR /paralogs/packages/back

CMD ["yarn", "start:dev"]