version: '3'
services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: paralogs-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg-password
    volumes:
      - ./pgdata/paragliding/test:/var/lib/postgresql/data

