version: '3'
services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "5443:5432"
    environment:
      POSTGRES_DB: paralogs-auth-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pg-password
    volumes:
      - ./pgdata/auth/test:/var/lib/postgresql/data

