version: 2.1
jobs:
  build:
    docker:
      - image: node:10.13.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn --freeze-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run:
          name: build-packages
          command: 'yarn build'
      # - run:
      #     name: back-tests
      #     command: 'cd packages/back; yarn ci:test;'
      - run:
          name: front-tests
          command: 'cd packages/front; yarn ci:test;'
