service: paralogs-api

custom:
  webpack:
    packager: yarn
  serverless-offline:
    port: 4000
  dynamodb:
    start:
      inMemory: true
      migrate: true
    stages:
      - dev
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}
  wingsTable: ${self:custom.stage}-wings-table

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-west-1
  environment:
    wingsTable: ${self:custom.wingsTable}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-west-1:*:*"

plugins:
  - serverless-dynamodb-local
  - serverless-plugin-monorepo
  - serverless-offline


functions:
  create-wing:
    handler: .build/infra/handlers/createWing.main
    events:
      - http:
          path: wings
          method: post
          cors: true
          authorizer: aws_iam
  list-wings:
      handler: .build/infra/handlers/listWings.main
      events:
        - http:
            path: wings
            method: get
            cors: true
            authorizer: aws_iam

  delete-wing:
    handler: .build/infra/handlers/deleteWing.main
    events:
      - http:
          path: wings/{id}
          method: delete
          cors: true
          authorizer: aws_iam

resources:
  - ${file(resources/dynamodb-wings.yml)}
  - ${file(resources/cognito-user-pool.yml)}
  - ${file(resources/cognito-identity-pool.yml)}
