name: CI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.13.0
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-
      run: yarn install --frozen-lockfile
    - name: Building packages
      run: yarn build
    - name: Backend tests
      run: cd packages/back; yarn ci:test;
    - name: Frontend tests
      run: cd packages/front; yarn ci:test;