name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.13.0
    - name: Current branch
      run: echo ${{ github.ref }}
    - name: Try condition
      if: github.ref != 'refs/heads/test-github-actions'
      run: echo 'it does not works'
    - name: Try oposite condition
      if: github.ref == 'refs/heads/test-github-actions'
      run: echo 'it does works'
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.cache/yarn/v6
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Building packages
      run: yarn build
    - name: Backend tests
      run: cd packages/back; yarn ci:test;
    - name: Frontend tests
      env:
        BACKEND_URL: http://localhost:4000/
      run: cd packages/front; yarn ci:test;